name: geo_monitor
description: Geo version 1.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  go_router: ^6.0.6
  firebase_auth: ^4.4.1
  firebase_messaging: ^14.4.0
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.11
  permission_handler: ^10.2.0
#  unicorndial: ^1.1.5
  path_provider: ^2.0.13
  provider: ^6.0.5
  material_design_icons_flutter: ^6.0.7096
  flutter_google_places: ^0.3.0
  intl: ^0.18.0
  http: ^0.13.5
  google_maps_flutter: ^2.2.5
  google_maps_webservice: ^0.0.19
  autocomplete_textfield: ^2.0.1
  location: ^4.4.0
  path: ^1.8.2
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2
  page_transition: ^2.0.9
  responsive_builder: ^0.6.4
  google_fonts: ^4.0.3
  image: ^4.0.16
  video_thumbnail: ^0.5.3
  android_intent: ^2.0.2
  flutter_credit_card: ^3.0.5
  uuid: ^3.0.7
  geocoding: ^2.0.5
  chewie: ^1.4.0
  camera: ^0.10.3+2
  maps_toolkit: ^2.0.1
  focused_menu: ^1.0.5
  universal_platform: ^1.0.0+1
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^2.0.0
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.6+4
  animations: ^2.0.7
  get: ^4.6.5
  hive: ^2.2.3
  fluttertoast: ^8.1.3
  georange: ^1.0.0
  geofence_service: ^3.5.0
  firebase_ui_auth: ^1.1.9
  firebase_dynamic_links: ^5.0.12
  flex_color_scheme: ^6.1.2
  flutter_riverpod: ^2.3.4
  native_device_orientation: ^1.1.4
  google_maps_utils: ^1.5.0+0
  google_maps_cluster_manager: ^3.0.0+1
  stream_channel: ^2.1.1
  badges: ^3.1.1
  map_launcher: ^2.5.0
  connectivity_plus: ^2.3.7
  dots_indicator: ^2.1.0
  flutter_libphonenumber: ^1.3.0
  firebase_crashlytics: ^3.0.12
  pin_code_fields: ^7.4.0
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.4.0
  record: ^4.4.4
  mic_stream: ^0.6.5
  audio_waveforms: ^1.0.4
  just_audio: ^0.9.31
  restart_app: ^1.1.2
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.1.1
  isolate_handler: ^1.0.2
  flutter_email_sender: ^5.2.0
  file_picker: ^5.2.9
  mime: ^1.0.4
  url_launcher: ^6.1.10
  archive: ^3.3.7
  lat_lng_to_timezone: ^0.2.0
  photo_view: ^0.14.0
  firebase_analytics: ^10.1.5
  siri_wave: ^0.3.0
  at_gauges: ^1.0.1
  fl_chart: ^0.61.0
  flutter_background_service: ^2.4.6
  device_info_plus: ^8.1.0
  webview_flutter: ^4.0.7
  shared_preferences: ^2.0.20
  audioplayers: ^3.0.1
#  adobe_xd: ^2.0.1
  video_player: ^2.6.1
  dio:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner:
  hive_generator:
  mockito: ^5.4.0

flutter:

  uses-material-design: true
  #  generate: true

  assets:
    - assets/intro/
    - assets/mapicons/
    - assets/l10n/
    - assets/
    - assets/projects/
    - .env
